source 'https://github.com/CocoaPods/Specs.git'

target 'AIQCoreLib', :exclusive => true do
  pod 'AIQCoreLib', :path => '../'
end

target 'Tests', :exclusive => true do
  pod 'AIQCoreLib', :path => '../'

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
