#ifndef AIQCoreLib_AIQLocation_h
#define AIQCoreLib_AIQLocation_h

#import <Foundation/Foundation.h>

/*!
 @header AIQLocation.h
 @author Marcin Lukow, Simon Jarbrant
 @copyright 2012 Appear Networks Systems AB
 @updated 2016-04-06
 @brief AIQLocation module can be used to distribute location events through NSNotificationCenter.
 @version 1.1.0
 */

@class CLLocation;

/** Location updated event name.

 This is the name of the event generated by NSNotificationCenter when location has been updated.
 
 @since 1.0.0
 */
EXTERN_API(NSString *) const AIQLocationUpdatedEvent;

/** Location failed event name.

 This is the name of the event generated by NSNotificationCenter when location could not be fetched.
 
 @since 1.0.0
 */
EXTERN_API(NSString *) const AIQLocationFailedEvent;

/** User info key for location after the update.

 This key is used to store a new user location. It can be used to retrieve the new location from the
 User Info map of the notification.
 
 @since 1.0.0
 @see AIQLocationUpdatedEvent
 */
EXTERN_API(NSString *) const AIQNewLocationKey;

/** User info key for location before the update.

 This key is used to store an old user location. It can be used to retrieve the old location from the
 User Info map of the notification.
 
 @since 1.0.0
 @see AIQLocationUpdatedEvent
 */
EXTERN_API(NSString *) const AIQOldLocationKey;

/** AIQLocation module singleton.

 This singleton can be used to check the user location. It can be achieved by either polling
 the singleton directly or by subscribing to AIQLocationUpdatedEvent events generated by NSNotificationCenter.
 
 @since 1.0.0

 @warning This module is intended to be used as a singleton.
 */
@interface AIQLocation : NSObject

/**---------------------------------------------------------------------------------------
 * @name Properties
 * ---------------------------------------------------------------------------------------
 */

/** Current user location.

 This property stores the latest recorded user location. May be nil if the AIQLocation singleton
 has not been started or if fetching location failed.
 
 @since 1.0.0
 */
@property (nonatomic, retain, readonly) CLLocation *currentLocation;

/**---------------------------------------------------------------------------------------
 * @name Static methods
 * ---------------------------------------------------------------------------------------
 */

/** Returns AIQLocation module instance.

 This static method can be used to retrieve the shared instance of the AIQLocation module singleton.

 @return AIQLocation module instance. Will not be nil.
 @since 1.0.0
 */
+ (id)instance;

/**---------------------------------------------------------------------------------------
 * @name Other methods
 * ---------------------------------------------------------------------------------------
 */

/** Starts monitoring significant location changes.

 This method can be used to tell the AIQLocation singleton to start monitoring significant location
 changes.
 
 @since 1.0.0
 
 @warning If the AIQLocation singleton was already running, it will rebroadcast the latest recorded location in order for
 the new caller to receive it.
*/
- (void)startMonitoringSignificantLocationChanges;

/** Stops monitoring significant location changes.

 This method can be used to tell the AIQLocation singleton that the caller is no longer interested
 in listening for significant location changes.
 
 @since 1.0.0
 
 @warning If startMonitoringSignificantLocationChanges method was called more than once, this method will not prevent the
 AIQLocation singleton from listening until the number of calls to this method will equal to the number of calls
 to  startMonitoringSignificantLocationChanges.
 */
- (void)stopMonitoringSignificantLocationChanges;

/** Pauses the AIQLocation singleton.

 This method can be used to pause monitoring significant location changes.
 
 @since 1.0.0
 */
- (void)pause;

/** Resumes the AIQLocation singleton.

 This method can be used to resume monitoring significant location changes after it has been paused.
 
 @since 1.0.0
 
 @warning If  startMonitoringSignificantLocationChanges method was called at least once before pausing the AIQLocation singleton,
 the latest recorded location will be rebroadcasted.
 */
- (void)resume;

@end

#endif /* AIQCoreLib_AIQLocation_h */
